---
title: "hw6"
author: "YuaoYang"
date: "2019/11/23"
output: github_document
---
```{r}
library(tidyverse)
library(modelr)
library(mgcv)
library(leaps)   
```


# Problem 1
```{r}
birthweight = read.csv("./data/birthweight.csv")%>% 
    janitor::clean_names() %>% 
  mutate(babysex = factor(babysex, levels = c(1,2), labels = c("male", "female")),
         frace = factor(frace, levels=c(1,2,3,4,8,9),labels = c("white", "black", "ssian", "puerto rican", "other", "unknown")),
         malform = factor(malform, levels = c(0,1), labels = c("absense", "present")),
         mrace = factor(mrace, levels = c(1, 2, 3, 4, 8, 9), labels = c("white", "black", "asian", "puerto rican", "other", "unknown"))
         )

any(is.na(birthweight))

```
From the function, we can find there is no missing value in this dataset.

```{r}
reg_all = lm(bwt~., data = birthweight) 
step(reg_all, direction='backward')

reg_optimal = lm(bwt ~ babysex + bhead + blength + delwt + fincome + 
    gaweeks + mheight + mrace + parity + ppwt + smoken, data = birthweight)
```
After i did the backward elimination test, I choose the smallest AIC model here.

```{r}
birthweight %>% 
  add_predictions(reg_optimal) %>% 
  add_residuals(reg_optimal) %>% 
  ggplot(aes(x = pred, y = resid)) + geom_point(alpha = 0.2,color = "black") + 
  geom_smooth(aes(y = resid), color = "red",method = "lm") +
  labs(x = "prediction", y = "residual", title = "model residuals against fitted values")
```

```{r}
reg_1 = lm(bwt~blength+gaweeks, data = birthweight)
reg_2 = lm(bwt~bhead+blength+babysex+bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = birthweight)
```

```{r}

cv_df = 
  crossv_mc(birthweight, 100) %>%
   mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) %>%
  mutate(reg_optimal  = map(train, ~lm(bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, data = .x)),
         reg_1     = map(train, ~lm(bwt~blength+gaweeks, data = .x)),
         reg_2  = map(train, ~gam(bwt~bhead+blength+babysex+bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = as_tibble(.x)))) %>% 
  mutate(rmse_reg_optimal = map2_dbl(reg_optimal, test, ~rmse(model = .x, data = .y)),
         rmse_reg_1   = map2_dbl(reg_1, test, ~rmse(model = .x, data = .y)),
         rmse_reg_2 = map2_dbl(reg_2, test, ~rmse(model = .x, data = .y)))
```

```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

# Problem 2

```{r}
weather_df =
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"),
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```

```{r}
 
bootstrap_weather = weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm( tmax ~ tmin , data = .x) ),
    results = map(models, broom::tidy),
    glance = map(models, broom::glance)) %>% 
  select(-strap, -models) %>% 
  unnest(results, glance)

weather_rsquare = bootstrap_weather %>%
  select(.id, r.squared) %>%
  unique()

weather_log = bootstrap_weather%>% 
  group_by(.id) %>% 
  mutate(log = log(estimate)) %>%  # becase log(a*b) = log(a) +log(b)
  summarise(log_sum = sum(log))
```

```{r}
weather_rsquare %>%
  ggplot(aes(x = r.squared)) +
  geom_density() +
  labs(title = "the distribution of R Squared", x = "R-Squared")

weather_log %>%
  ggplot(aes(x = log_sum))+geom_density() +
  labs(x = "log(beta0*beta1)", title = "the distribution of log(beta0*beta1)")
```

```{r}
quantile(pull(weather_rsquare, r.squared), c(0.025, 0.975))
quantile(pull(weather_log, log_sum), c(0.025, 0.975))
```

From the calculation, we can find that provide 95% confidence interveal the range is (0.894,0.927) for R Squared given 2.5% and 97.5% quantiles, and it is (1.97, 2.06) for log(beta0*beta1).